name: telegram_userbot_dart
description: Telegram userbot Dart. 
version: 0.0.0
homepage: https://youtube.com/@azkadev
repository: https://github.com/azkadev/telegram_userbot_dart
issue_tracker: https://github.com/azkadev/telegram_userbot_dart 



environment:
  sdk: '>=2.18.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  path: ^1.8.2
  telegram_client: ^0.3.71